name: API Sync

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: 'poetry'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: poetry run python build_queries.py
